# Project-wide Gradle settings.

# JVM memory settings for Gradle Daemon
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Xss16m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# 🟢 إعدادات ذاكرة مترجم كوتلن لحل مشكلة StackOverflowError نهائياً
kotlin.daemon.jvmargs=-Xmx2048m -Xss16m
kotlin.compiler.execution.strategy=in-process

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Flipper version
FLIPPER_VERSION=0.125.0

# Architecture configuration
reactNativeArchitectures=armeabi-v7a,arm64-v8a

# New Architecture flag
newArchEnabled=false

android.disableAutomaticComponentCreation=true

# Signing keys
MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=
MYAPP_UPLOAD_KEY_PASSWORD=

org.gradle.daemon=false
org.gradle.parallel=false
