name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone original working repo
        run: |
          git clone --depth 1 https://github.com/penteleichuk/SAMP-Mobile-Launcher-RN.git original

      - name: Checkout YOUR custom files
        uses: actions/checkout@v4
        with:
          path: fork

      - name: Merge your custom files into original
        run: |
          cp -r fork/src/* original/src/ 2>/dev/null || true
          cp -r fork/assets/* original/assets/ 2>/dev/null || true
          cp -r fork/distribution/* original/distribution/ 2>/dev/null || true
          cp fork/.env original/.env 2>/dev/null || true
          cp fork/app.json original/app.json 2>/dev/null || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd original
          npm install -g yarn
          rm -rf node_modules yarn.lock
          yarn install --ignore-engines

      - name: Install extra packages for your custom src
        run: |
          cd original
          yarn add react-native-worklets @react-navigation/bottom-tabs @gorhom/bottom-sheet @react-native-async-storage/async-storage @react-navigation/native-stack react-native-bootsplash react-native-gesture-handler react-native-safe-area-context react-native-screens react-native-reanimated react-native-vector-icons react-native-linear-gradient react-native-fs react-native-device-info react-native-fast-image react-native-progress react-native-shadow-2 react-native-size-matters react-native-snowflakes react-native-svg react-native-svg-icon react-native-switch lottie-react-native react-native-animated-nav-tab-bar react-native-awesome-alerts react-native-reanimated-carousel react-native-quick-base64 react-native-zip-archive axios ini buffer styled-components react-redux redux redux-thunk @notifee/react-native @react-native-community/blur @react-native-community/masked-view @react-native-firebase/app @react-native-firebase/crashlytics @react-native-firebase/messaging @sayem314/react-native-keep-awake @sharcoux/slider @dominicvonk/react-native-apk-installer --ignore-engines

      - name: Make gradlew executable
        run: chmod +x original/android/gradlew

      - name: Build JS Bundle manually
        run: |
          cd original
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle

      - name: Build Release APK
        run: cd original/android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: original/android/app/build/outputs/apk/release/*.apk
